apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap-discovery.yaml
- deployment-hat.yaml
- deployment-left-arm.yaml
- deployment-left-leg.yaml
- deployment-entry.yaml
- deployment-right-arm.yaml
- deployment-right-leg.yaml
- service-hat.yaml
- service-left-arm.yaml
- service-left-leg.yaml
- service-entry.yaml
- service-right-arm.yaml
- service-right-leg.yaml
- serviceaccount.yaml

commonLabels:
  app.kubernetes.io/name: podtato-head

