# patch.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-main
spec:
  template:
    spec:
      containers:
        - name: podtato-head-entry
          image: ghcr.io/podtato-head/entry:latest
