apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
      annotationSelector: deimos.io/environment-staging notin (deploy)
    patch: |
      $patch: delete
      kind: Application
      metadata:
        name: DOES NOT MATTER
resources:
  - ../base
