---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    deimos.io/customer: deimos.io
    deimos.io/owner: sre@deimos.io
    deimos.io/project: managed-infrastructure  
    deimos.io/environment-local: deploy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: deimos.io
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.1
    chart: external-secrets
    helm:
      releaseName: external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
