---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger-operator
  namespace: argocd
  annotations:
    deimos.io/application: observability
    deimos.io/customer: deimos.io
    deimos.io/owner: sre@deimos.io
    deimos.io/project: managed-infrastructure 
    deimos.io/environment-local: deploy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: deimos.io
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    targetRevision: 2.46.1
    chart: jaeger-operator
    helm:
      releaseName: jaeger-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
